### ISSUE TITLE
Error encountered when running "alembic revision --autogenerate"

### ISSUE THREAD

**Issue by viewsdevelop** [learn-co-curriculum/python-p3-sqlalchemy-many-to-many#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204246?module_item_id=468036

### Concern

**"Many-to-Many with `Table` Objects"** 

Error encountered when issuing `alembic revision --autogenerate -m 'Add game_user Association Table'`:

`InvalidRequestError: Table 'game_users' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.`

### Suggested Changes

To fix, add `extend_existing=True` to `game_user` Table instance arguments like so before re-running command:

`game_user = Table(
    'game_users',
    Base.metadata,
    Column('game_id', ForeignKey('games.id'), primary_key=True),
    Column('user_id', ForeignKey('users.id'), primary_key=True),
    extend_existing=True)`

See docs [here](https://docs.sqlalchemy.org/en/14/core/metadata.html#sqlalchemy.schema.Table.params.extend_existing).

**Comment by professor-ben** [comment]
This is super helpful. Working through the code challenge now and seeing what they have to do to keep pace with the Ruby curriculum, I think this lesson needs some significant changes.
