### ISSUE TITLE
Cannot Run Pytest, Fails CodeGrade

### ISSUE THREAD

**Issue by jessicavaughn619** [learn-co-curriculum/python-p3-sqlalchemy-many-to-many#10]
### Canvas Link

https://learning.flatironschool.com/courses/6192/assignments/231632?module_item_id=542403

### Concern

I am not able to run pytest in this lab. My solution code matches the provided code-along solution code, but fails CodeGrade test.

**Comment by professor-ben** [comment]
Hi Jessica,

Have you tried pairing with a TC? We did make some recent changes here so it's definitely possible there's an issue, but I think the TCs might be able to hammer it out for you.

Thanks,
Ben

**Comment by jessicavaughn619** [comment]
I have not connected with a TC on this lab, yet. I will try that!

Thank you,

Jessica

**Comment by professor-ben** [comment]
Hi Jessica,

I'm reassigning this to our resident CodeGrade expert, Prabhdip. He should be able to help out if the TCs are stuck!

-Ben

**Comment by jessicavaughn619** [comment]
Thank you! I was able to solve my issue by going through the full time solution code for a similar lab.

Jessica

**Comment by pgill97** [comment]
> Thank you! I was able to solve my issue by going through the full time solution code for a similar lab. Jessica
> […](#)
> On Apr 5, 2023 at 12:04 PM -0600, professor-ben ***@***.***>, wrote: Hi Jessica, I'm reassigning this to our resident CodeGrade expert, Prabhdip. He should be able to help out if the TCs are stuck! -Ben — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Closing because issue resolved.
