### ISSUE TITLE
Reference Code In Image missing code

### ISSUE THREAD

**Issue by Preston-Hunter** [learn-co-curriculum/python-p3-sqlalchemy-many-to-many#11]
### Canvas Link

https://learning.flatironschool.com/courses/6266/assignments/232461?module_item_id=544989

### Concern

Association Object Model Image is missing referenced code in the Review class
    game = relationship('Game', back_populates='reviews')
    user = relationship('User', back_populates='reviews')
This code is present in the solution branch on github

**Comment by professor-ben** [comment]
Hi Preston,

Thanks for the report! This should be fixed in GitHub, and will soon be visible in Canvas as well.

-Ben
