### ISSUE TITLE
Text says to look for app folder when none exists

### ISSUE THREAD

**Issue by Fakishki** [learn-co-curriculum/python-p3-sqlalchemy-many-to-many#12]
### Canvas Link

https://learning.flatironschool.com/courses/6274/assignments/236191?module_item_id=554170

### Concern

Search the text here for "You can use the script in app/seed_2.py to generate new data and interact with your database through the Python shell."

You'll see in the files themselves, there is no "app" folder.   seed_2.py lives in the lib folder.

**Comment by professor-ben** [comment]
Thanks for the report! I think we talked about the origin story here the other day- we decided to rename all code directories in phase 3 to `lib/` some time ago. We missed it in the README here.

Thanks again,
Ben
