### ISSUE TITLE
Struggled to get this off the ground

### ISSUE THREAD

**Issue by baschenbrenner** [learn-co-curriculum/python-p3-sqlalchemy-many-to-many#6]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204246?module_item_id=468036

### Concern

I struggled to get the migrations going - my solution was eventually to delete the migrations folder and the alembic.ini and just do it again. I notice that the current migrations folder has nothing in the versions folder. Not sure if this is relevant.

**Comment by professor-ben** [comment]
That doesn't sound quite right- it should be building on the previous lab. I'll get on this next week.

-Ben

**Comment by foreverluiscastro** [comment]
I have also run into this issue. My only option was to delete the migration files and re-do the process but I wanted to double back on this to see what should be done moving forward.

**Comment by professor-ben** [comment]
@foreverluiscastro is this still occurring when you clone the repo down new? I pushed a change recently that should have fixed it, but there might still be some version control issues going on.
