### ISSUE TITLE
#User model is commented out in debug.py

### ISSUE THREAD

**Issue by sbalayan1** [learn-co-curriculum/python-p3-sqlalchemy-many-to-many#7]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204246?module_item_id=468036

### Concern

If you try to query for the Users table in debug.py, you hit an error that says the User table doesn't exist. This is because User is commented out from the import in debug.py. Not sure if this was intentional or not.

**Comment by professor-ben** [comment]
This was intentional because it wasn't created yet, but I'll look for a better approach so that students don't run into this issue.

**Comment by sbalayan1** [comment]
If anything I think just a note in the lesson about uncommenting the User model would suffice.
