### ISSUE TITLE
Creating created_at and updated_at columns after initial migrations results in the below error

### ISSUE THREAD

**Issue by sbalayan1** [learn-co-curriculum/python-p3-sqlalchemy-many-to-many#8]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/204246?module_item_id=468036

### Concern

After working through the lab, I realized I needed to have created_at and updated_at columns in each table. I added those columns to my models and created a migration to update my database. The migrations work fine but upon upgrading head, hit the following error.

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) Cannot add a column with non-constant default

Seems adding a timestamp column is a no, no. My current work around is ensuring I have those columns in the initial migration of users, reviews, and games. Would recommend a warning in the reading.

**Comment by professor-ben** [comment]
Another fun quirk in SQLAlchemy! I'll try to reproduce this and add a warning based on what comes out of it.

Thanks,
Ben

**Comment by professor-ben** [comment]
Looks like this is actually a SQLite problem- what a relief! We're switching to Postgres soon, but I will add a warning either way.
